### ISSUE TITLE
Where can I download dataset for training?

### ISSUE THREAD

**Issue by jun-ja** [autonomousvision/neat#1]
Thank you for providing a good code.
Where can I download dataset for training?
I referred to the config.py, but it seems to be different from the transfuser dataset. Transfuser provides Town0x_long, Town0x_short, and Town0x_tiny but it requires Town0x, Town0x_long, and Town0x_small.

**Comment by kashyap7x** [comment]
We used the same routes for generating data for both the Transfuser and NEAT projects, but renamed the data folders. Town0x is Town0x_short from Transfuser, and Town0x_small is Town0x_tiny from Transfuser. Town0x_long is used for validation. It should be possible to train using the `14_weathers_data` from Transfuser.

**Comment by jun-ja** [comment]
Thank you for your answer!
