### ISSUE TITLE
Could you provide data for training ?

### ISSUE THREAD

**Issue by promesse** [autonomousvision/neat#14]
![image](https://user-images.githubusercontent.com/26239060/204992917-9b878645-f478-42c0-98ab-32d40caad25f.png)
Readme does not seem to provide a download link for the data.
Thanks

**Comment by kashyap7x** [comment]
The `14_weathers_data` from the CVPR2021 branch of TransFuser can also be used to train NEAT. You can download the data by following the [instructions on the TransFuser repo](https://github.com/autonomousvision/transfuser/tree/cvpr2021#dataset).

Se also https://github.com/autonomousvision/neat/issues/9#issuecomment-1077535092

**Comment by promesse** [comment]
Thanks for your reply
you mean thease data?
![image](https://user-images.githubusercontent.com/26239060/205228840-9185ad67-7d9c-4a7b-9a91-d29f01cbf0ef.png)

**Comment by promesse** [comment]
> The `14_weathers_data` from the CVPR2021 branch of TransFuser can also be used to train NEAT. You can download the data by following the [instructions on the TransFuser repo](https://github.com/autonomousvision/transfuser/tree/cvpr2021#dataset).
> 
> Se also [#9 (comment)](https://github.com/autonomousvision/neat/issues/9#issuecomment-1077535092)
Thank you for your reply.
You mean these data in TransFuser download_data script?
![image](https://user-images.githubusercontent.com/26239060/205229339-39091fa6-f567-46db-a5a4-ffc76777475b.png)

**Comment by kashyap7x** [comment]
No, I meant the `14_weathers_data` from the cvpr2021 branch. The image you linked contains the dataset used in our PAMI follow-up paper, which is not directly compatible with the NEAT code.

Here is the bash script with URLs for the `14_weathers_data` that can be used to train NEAT:
https://github.com/autonomousvision/transfuser/blob/9d5ebf01f7b5f6e5c02ebe0cba423119c465b388/download_data.sh#L39
