### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../carla_results/auto_pilot.json'

### ISSUE THREAD

**Issue by ZHICHENG12** [autonomousvision/neat#15]
**when i  Running the Autopilot**

./leaderboard/scripts/run_evaluation.sh

**i accept this error :** 

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 477, in main
    leaderboard_evaluator.run(arguments)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 406, in run
    self.statistics_manager.clear_record(args.checkpoint)
  File "/home/ev/Net/carla_prj/neat/leaderboard/leaderboard/utils/statistics_manager.py", line 340, in clear_record
    with open(endpoint, 'w') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '../carla_results/auto_pilot.json'
Exception ignored in: <function LeaderboardEvaluator.__del__ at 0x7fe8e9a8a9e0>

**can you help? thank you very much**

**Comment by ZHICHENG12** [comment]
i want to generate data, how should i set the json file?

**Comment by kashyap7x** [comment]
For the first question, maybe you need to create the `carla_results` folder if the path does not exist.

For generating the data, you only need to uncomment this line in `run_evaluation.sh`:
https://github.com/autonomousvision/neat/blob/349878952bca75970f1f7ab36f27995ba352aa6f/leaderboard/scripts/run_evaluation.sh#L28

The json file which stores the results should be created automatically, you do not need to set it.

If you do not require a customized dataset and simply want to download a dataset that is compatible with the NEAT code for training, see https://github.com/autonomousvision/neat/issues/14#issuecomment-1335526566
