### ISSUE TITLE
How to generate training data for different model

### ISSUE THREAD

**Issue by hu-jerry** [autonomousvision/neat#3]
Hi,
Thanks for the interesting work ! 

I follow the step of Data Generation provides in the README file, "./leaderboard/scripts/run_evaluation.sh" to  run the Autopilot.
But I havesome questions,as the following :
(1) this process  is only to evaluate the performance of different agents on the defined routes. No data was generated.
(2) different models (agent) need different types of data. I want to know how to generate training data for different models.

Any tips would be helpful.

Thanks in advance!

**Comment by ap229997** [comment]
1. You can assign the desired location to save data to the `SAVE_PATH` variable in [./leaderboard/scripts/run_evaluation.sh](https://github.com/autonomousvision/neat/blob/main/leaderboard/scripts/run_evaluation.sh#L28) to generate data.
2. The data is generated only once for all the models and it contains all the required modalities for all the models.
