### ISSUE TITLE
How to get the visualization results as shown in README

### ISSUE THREAD

**Issue by chhanganivarun** [autonomousvision/neat#4]
I am not able to replicate the gif shown in README wherein you are able to visualize waypoint offsets too along with dashcam and semantic segmentation from BEV.

Could you please share the scripts for the same?

**Comment by kashyap7x** [comment]
If you provide a SAVE_PATH while evaluating NEAT, the RGB image, semantics and waypoint offsets all get saved to your disk: https://github.com/autonomousvision/neat/blob/686f4a0b5b5bf20c99f323e9542f5b68808df2de/leaderboard/team_code/neat_agent.py#L266

We created the visualization in the gif using a video editing tool (https://kdenlive.org/en/), and not through a script.
