### ISSUE TITLE
4 waypoints used instead of 5?

### ISSUE THREAD

**Issue by cozeybozey** [autonomousvision/neat#5]
Hi,
I am taking a look at your code and I noticed you predict 5 waypoints in the decoder network, but you only use 4 waypoints for actually controlling the car. You do not use the first predicted waypoint and I was wondering why you would do that.

Thanks in advance!

**Comment by ap229997** [comment]
The decoder predicts the current timestep and 4 future timesteps and we require the future timesteps predictions for controller.
