### ISSUE TITLE
Data Generation via `run_evaluation.sh`

### ISSUE THREAD

**Issue by lzhnb** [autonomousvision/neat#6]
Hi,
Thanks for the amazing work!
I followed the **Data Generation** section in `README.md`(I did not modify any configurations and just activated the export of `SAVE_PATH` in the script).
The following video shows the generated front images:

![temp_](https://user-images.githubusercontent.com/49898493/153024229-f302809f-1120-45de-83c7-6686311fa4f4.gif)

| As shown in the above video, the weather is changing, and this example(as one **RouteScenario**) consists of **94** frames (Different scenarios have different frames).

For some scenarios, they met the failures like the followings:
<img width="402" alt="Snipaste_2022-02-08_23-57-16" src="https://user-images.githubusercontent.com/49898493/153025527-31219106-4aa7-4827-8166-47c0df468189.png">

Does it work? Is there anything wrong with this?

**Comment by ap229997** [comment]
This is fine. There are some cases when the vehicles in front of the ego-vehicle get stuck due to which the ego-vehicle does not move, resulting in agent blocked error.

**Comment by lzhnb** [comment]
After running the `run_evaluation.sh` to generate the dataset. I get the dataset directories like `carla_results/auto_pilot_eval/eval_routes_weathers_02_...`
<img width="1039" alt="Snipaste_2022-02-11_00-32-50" src="https://user-images.githubusercontent.com/49898493/153452636-ee32b97a-e7f7-4f8b-ab2f-d810604989c4.png">


However, I find the config of training in `neat/config.py`:
```python
class GlobalConfig:
    """ base architecture configurations """

	# Data
    root_dir = '/is/rg/avg/kchitta/carla9-10_data/2021/apv3'
    train_towns = ['Town01', 'Town02', 'Town03', 'Town04', 'Town05', 'Town06', 'Town07', 'Town10']
    val_towns = ['Town01_long', 'Town02_long', 'Town03_long', 'Town04_long', 'Town05_long', 'Town06_long']
    train_data, val_data = [], []
    for town in train_towns:
        train_data.append(os.path.join(root_dir, town))
        train_data.append(os.path.join(root_dir, town+'_small'))
    for town in val_towns:
        val_data.append(os.path.join(root_dir, town))
```

Obviously, there should be some directories like `carla_results/auto_pilot_eval/Town...`

How can I get such results?

**Comment by ap229997** [comment]
You need to generate data for each town separately by setting the `ROUTES` variable in `run_evaluation.sh` to the corresponding [routes file](https://github.com/autonomousvision/neat/tree/main/leaderboard/data/training_routes).

**Comment by lzhnb** [comment]
> You need to generate data for each town separately by setting the `ROUTES` variable in `run_evaluation.sh` to the corresponding [routes file](https://github.com/autonomousvision/neat/tree/main/leaderboard/data/training_routes).

Thanks, so I need to So set all the files‘ names under `leaderboard/data/training_routes` to `ROUTE` variable in `run_evaluation.sh` and run this script to generate the training data, right?

What I am concerned about now is how much time and space it will take to generate this dataset?

**Comment by ap229997** [comment]
> Thanks, so I need to So set all the files‘ names under `leaderboard/data/training_routes` to `ROUTE` variable in `run_evaluation.sh` and run this script to generate the training data, right?

That's right.

> What I am concerned about now is how much time and space it will take to generate this dataset?

It took us 2-3 days to generate the data on 8 1080Ti GPUs and the total size was around 400G.

**Comment by lzhnb** [comment]
> > Thanks, so I need to So set all the files‘ names under `leaderboard/data/training_routes` to `ROUTE` variable in `run_evaluation.sh` and run this script to generate the training data, right?
> 
> That's right.
> 
> > What I am concerned about now is how much time and space it will take to generate this dataset?
> 
> It took us 2-3 days to generate the data on 8 1080Ti GPUs and the total size was around 400G.

Thanks for your quick reply!
Does **8 1080Ti GPUS** mean that running 8 CARLA servers individually, and each server is responsible for one route file?

**Comment by ap229997** [comment]
Yes
