### ISSUE TITLE
Effects of semantic

### ISSUE THREAD

**Issue by Watson52** [autonomousvision/neat#7]
Thanks for the work and the open source code. In the controller, I know that the use of red light for the longitudinal controller. But what if just use raw data input of RGB to identify instead of semantic? Could you please tell me the affect of the semantic? That is I think the semantic is just use to identify the traffic light.

**Comment by ap229997** [comment]
Semantic loss is also crucial for training our model. You can see in Table 3 our [supplementary material](http://www.cvlibs.net/publications/Chitta2021ICCV_supplementary.pdf) that there is a significant drop in performance when we remove the semantic loss.
