### ISSUE TITLE
Is the dataset in neat the same as transfuser?

### ISSUE THREAD

**Issue by exiawsh** [autonomousvision/neat#8]
Hello,
Thanks for your wonderful work!
I have doubt with the data generation,
Is the dataset in this work the same as in transfuser?
Shall I download the data in https://s3.eu-central-1.amazonaws.com/avg-projects/transfuser/data/14_weathers_minimal_data.zip and directly use it?
And what's the data format for query_points? just simple (x,y,t)->(2,5,1) as in the paper described? If the semantic map range is huge, did you normalize the input data?

**Comment by ap229997** [comment]
The dataset used for training models in this repo is different than the `14_weathers_minimal_data` from the transfuser repo. The details regarding the dataset are provided in Sec. 2.5 of the [supplementary](http://www.cvlibs.net/publications/Chitta2021ICCV_supplementary.pdf).

The BEV semantics and waypoint prediction are always in the coordinate frame with the ego-vehicle at the bottom center and the query points are in (x,y,t) format.
